import { z } from 'zod';
import { stringArraySchema, highlightsSchema } from './shared';

export const universitySchema = z.object({
  slug: z.string().min(1, 'Slug is required'),
  name: z.string().min(1, 'Name is required'),
  nameCn: z.string().default(''),
  city: z.string().min(1, 'City is required'),
  cityCn: z.string().default(''),
  ranking: z.coerce.number().int().min(1, 'Ranking must be a positive integer'),
  rating: z.coerce.number().min(0).max(5).default(0),
  type: z.string().min(1, 'Type is required'),
  typeCn: z.string().default(''),
  established: z.coerce.number().int().min(1000).max(2100),
  students: z.string().default(''),
  intlStudents: z.string().default(''),
  description: z.string().min(1, 'Description is required'),
  descriptionCn: z.string().default(''),
  popularPrograms: stringArraySchema,
  popularProgramsCn: stringArraySchema,
  tuitionUndergrad: z.string().default(''),
  tuitionGraduate: z.string().default(''),
  intake: z.string().default(''),
  intakeCn: z.string().default(''),
  disciplines: stringArraySchema,
  image: z.string().min(1, 'Image is required'),
  logo: z.string().default(''),
  qsRanking: z.string().default(''),
  qsWorldRanking: z.coerce.number().int().default(0),
  tags: stringArraySchema,
  tagsCn: stringArraySchema,
  accommodation: z.string().default(''),
  accommodationCn: z.string().default(''),
  accommodationCost: z.string().default(''),
  accommodationCostCn: z.string().default(''),
  accommodationTypes: stringArraySchema,
  accommodationTypesCn: stringArraySchema,
  gallery: stringArraySchema,
  highlights: highlightsSchema.default({ en: [], zh: [] }),
  scholarshipInfo: z.string().optional(),
  scholarshipInfoCn: z.string().optional(),
  applicationDeadline: z.string().optional(),
});

export type UniversityInput = z.infer<typeof universitySchema>;
