-- ============================================================================
-- Phase 46: lead-system extensions for WhatsApp automation
--
-- Three changes in one migration so the deploy is a single SQL run:
--
-- 1. lead_history.action enum — extend to include 4 new WhatsApp-specific
--    actions so the lead detail page and the future bulk-send report can
--    filter "show all auto-welcomes" or "show all intake reminders"
--    without parsing the free-text `note` column.
--
--    'contacted' stays for the manual admin Send button (Phase 45a) — a
--    human initiated the send. The new actions are all system-initiated.
--
--    New actions:
--      whatsapp_welcome_sent          - auto-welcome on lead creation
--      whatsapp_status_sent           - application status change notify
--      whatsapp_promo_sent            - bulk promotional blast
--      whatsapp_intake_reminder_sent  - 30-day intake deadline reminder
--
-- 2. bump_contact_attempts trigger — extend to fire for the new actions
--    too (so the leads' `last_contacted_at` + `contact_attempts` columns
--    stay accurate regardless of which channel/initiator sent).
--
-- 3. do_not_contact column on the 3 lead tables — opt-out flag for the
--    future 2-way inbox (Phase 45c) and any manual suppressions. Every
--    WABPO fire path skips rows where this is TRUE.
--
-- Backwards-compatible: existing 'contacted' rows are unaffected. The new
-- enum values only apply to new rows inserted after this migration.
-- ============================================================================

-- Drop the existing constraint. The name is auto-generated by Postgres
-- (table_column_check pattern) for inline CHECK clauses.
ALTER TABLE lead_history
  DROP CONSTRAINT IF EXISTS lead_history_action_check;

-- Recreate with the expanded set. Idempotent if applied twice (after the
-- first drop above, the new constraint is always created).
ALTER TABLE lead_history
  ADD CONSTRAINT lead_history_action_check
  CHECK (action IN (
    -- existing (Phase 2.1)
    'status_changed',
    'notes_updated',
    'assigned',
    'unassigned',
    'contacted',
    'created',
    -- new (Phase 46)
    'whatsapp_welcome_sent',
    'whatsapp_status_sent',
    'whatsapp_promo_sent',
    'whatsapp_intake_reminder_sent'
  ));

-- ----------------------------------------------------------------------------
-- Trigger update: bump_contact_attempts() — extend to fire for all
-- whatsapp_* actions, not just 'contacted'. Auto-welcome, status notify,
-- bulk-promo, and intake reminders all count as outreach to the lead.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.bump_contact_attempts()
RETURNS TRIGGER AS $$
DECLARE
  tbl text;
BEGIN
  -- Outreach-style actions (manual + every system-initiated WhatsApp send)
  IF NEW.action IN (
    'contacted',
    'whatsapp_welcome_sent',
    'whatsapp_status_sent',
    'whatsapp_promo_sent',
    'whatsapp_intake_reminder_sent'
  ) THEN
    tbl := CASE NEW.lead_type
      WHEN 'contact' THEN 'contact_submissions'
      WHEN 'chat' THEN 'chat_leads'
      WHEN 'assessment' THEN 'student_assessments'
    END;
    IF tbl IS NOT NULL THEN
      EXECUTE format(
        'UPDATE %I SET contact_attempts = COALESCE(contact_attempts, 0) + 1, last_contacted_at = NOW() WHERE id = $1',
        tbl
      ) USING NEW.lead_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ----------------------------------------------------------------------------
-- do_not_contact column on the 3 lead tables. Set when:
--   - The lead replies STOP in a future 2-way inbox (Phase 45c)
--   - The lead reports spam manually
--   - The lead's number bounces repeatedly
--
-- Every WABPO fire path (fireAndForget, status-change, bulk-send,
-- intake-reminder) MUST skip leads where this is true. Future PRs
-- will thread the filter through.
-- ----------------------------------------------------------------------------
ALTER TABLE contact_submissions
  ADD COLUMN IF NOT EXISTS do_not_contact BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE chat_leads
  ADD COLUMN IF NOT EXISTS do_not_contact BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE student_assessments
  ADD COLUMN IF NOT EXISTS do_not_contact BOOLEAN NOT NULL DEFAULT FALSE;

-- Partial indexes — the filter for "active leads" is the hot path.
CREATE INDEX IF NOT EXISTS idx_contact_submissions_active
  ON contact_submissions(created_at DESC) WHERE NOT do_not_contact;
CREATE INDEX IF NOT EXISTS idx_chat_leads_active
  ON chat_leads(created_at DESC) WHERE NOT do_not_contact;
CREATE INDEX IF NOT EXISTS idx_student_assessments_active
  ON student_assessments(created_at DESC) WHERE NOT do_not_contact;
