-- ============================================================================
-- S8: Transcript storage bucket + RLS
-- ============================================================================
--
-- Creates the `transcripts` bucket used by the /assessment form signed-URL
-- upload flow. The assessment form uploads the transcript BEFORE the final
-- submission, so the bucket must allow signed-URL uploads from unauthenticated
-- visitors (the signed token itself is the authorization).
--
-- Path layout: transcripts/assessments/{uuid}/{safeName}.{ext}
-- The uuid is generated by the server when the signed URL is requested;
-- the final assessment row stores the path in transcript_storage_path.

-- ----------------------------------------------------------------------------
-- 1. Bucket
-- ----------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'transcripts',
  'transcripts',
  false,                                  -- private bucket
  10485760,                               -- 10MB per file
  ARRAY[
    'application/pdf',
    'image/png',
    'image/jpeg',
    'image/jpg',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- ----------------------------------------------------------------------------
-- 2. Storage RLS policies
-- ----------------------------------------------------------------------------
-- Signed upload URLs bypass the need for an INSERT policy: the token embedded
-- in the URL authorizes the PUT. We still need SELECT policies so admins can
-- download transcripts for review, and a cleanup policy so the service role
-- can delete orphaned files.

-- Admins can read any transcript in the bucket.
CREATE OR REPLACE FUNCTION public.is_admin_for_storage()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM admin_profiles
    WHERE user_id = auth.uid()
      AND is_active = true
      AND role IN ('admin', 'super_admin')
  );
$$;

DROP POLICY IF EXISTS "Admins can read all transcripts" ON storage.objects;
CREATE POLICY "Admins can read all transcripts"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'transcripts'
    AND public.is_admin_for_storage()
  );

-- Service role / bucket owner can delete transcripts (orphan cleanup).
DROP POLICY IF EXISTS "Service role can delete transcripts" ON storage.objects;
CREATE POLICY "Service role can delete transcripts"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'transcripts'
    AND public.is_admin_for_storage()
  );
