import { NextRequest, NextResponse } from 'next/server';
import { requireAdmin, buildServiceClient, getServerEnv } from '@/lib/supabase-auth';
import { insertTimelineEvent } from '@/lib/timeline';
import { mapApplicationFromDb } from '@/lib/application-mapper';
import { notifyApplicantOnStatusChange } from '@/lib/email';

const ALLOWED_STATUSES = [
  'Draft', 'Submitted', 'Under Review', 'Documents Requested',
  'Decision Made', 'Accepted', 'Rejected', 'Withdrawn',
] as const;

/**
 * S29: student notification title (in-app inbox). The full message
 * body is generated by studentNotificationMessage. These mirror the
 * email subject lines so the user sees the same headline in both
 * channels.
 */
function studentNotificationTitle(newStatus: string): string {
  switch (newStatus) {
    case 'Submitted':           return 'Application submitted';
    case 'Under Review':        return 'Application under review';
    case 'Documents Requested': return 'Documents requested';
    case 'Decision Made':       return 'A decision has been made';
    case 'Accepted':            return '🎉 Application accepted';
    case 'Rejected':            return 'Application rejected';
    case 'Withdrawn':           return 'Application withdrawn';
    case 'Draft':               return 'Application moved to draft';
    default:                    return `Application status: ${newStatus}`;
  }
}

function studentNotificationMessage(
  newStatus: string,
  university: string,
  program: string | null,
): string {
  const at = program ? `${university} — ${program}` : university;
  switch (newStatus) {
    case 'Submitted':           return `Your application to ${at} has been received and queued for review.`;
    case 'Under Review':        return `The SICA team is now reviewing your application to ${at}.`;
    case 'Documents Requested': return `SICA needs more documents for your application to ${at}. Please log in to upload them.`;
    case 'Decision Made':       return `A decision has been made on your application to ${at}. Check the application for details.`;
    case 'Accepted':            return `Great news — your application to ${at} was accepted! We'll email the next steps shortly.`;
    case 'Rejected':            return `Unfortunately, your application to ${at} was not successful this time. The reasons are in the application detail.`;
    case 'Withdrawn':           return `Your application to ${at} has been withdrawn.`;
    case 'Draft':               return `Your application to ${at} was moved back to draft.`;
    default:                    return `Your application to ${at} is now ${newStatus}.`;
  }
}

/**
 * GET    /api/admin/applications/[id]
 * PATCH  /api/admin/applications/[id]  — update status, notes, etc.
 * DELETE /api/admin/applications/[id]  — cancel (status='Withdrawn')
 */
export async function GET(
  request: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  if (!getServerEnv().serviceKey) {
    return NextResponse.json({ error: 'Supabase not configured' }, { status: 503 });
  }
  const auth = await requireAdmin(request);
  if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status });

  const { id } = await context.params;
  if (!id) return NextResponse.json({ error: 'Missing id' }, { status: 400 });

  try {
    const service = buildServiceClient();
    const { data, error } = await service
      .from('student_applications')
      .select('*, student:student_profiles!student_id (id, first_name, last_name, email, source, status)')
      .eq('id', id)
      .maybeSingle();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }
    if (!data) {
      return NextResponse.json({ error: 'Application not found' }, { status: 404 });
    }
    // Normalize to the same shape the list endpoint returns
    return NextResponse.json({ application: mapApplicationFromDb(data) });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

export async function PATCH(
  request: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  if (!getServerEnv().serviceKey) {
    return NextResponse.json({ error: 'Supabase not configured' }, { status: 503 });
  }
  const auth = await requireAdmin(request);
  if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status });

  const { id } = await context.params;
  if (!id) return NextResponse.json({ error: 'Missing id' }, { status: 400 });

  try {
    const body = await request.json();

    // Phase 109 Batch 5: restore action. Companion to the DELETE
    // handler that sets status='Withdrawn'. Restoring re-opens the
    // row as 'Submitted' (so the lifecycle continues from the
    // queue side) and writes a stage_history event so the timeline
    // tab surfaces it.
    //
    // Body: { action: 'restore' }
    //
    // Refuses to restore rows that aren't Withdrawn (only terminal-
    // undo-able state) — if the admin wants to re-open an
    // Accepted/Under Review row they should just edit it normally.
    if (body && typeof body === 'object' && (body as { action?: string }).action === 'restore') {
      const service = buildServiceClient();
      // Read the current status to refuse non-Withdrawn rows + capture
      // from_status for the stage_history event.
      const { data: existing } = await service
        .from('student_applications')
        .select('id, status')
        .eq('id', id)
        .maybeSingle();
      if (!existing) {
        return NextResponse.json({ error: 'Application not found' }, { status: 404 });
      }
      const fromStatus = (existing as { status: string }).status;
      if (fromStatus !== 'Withdrawn') {
        return NextResponse.json(
          { error: `Cannot restore a row in status '${fromStatus}' (only Withdrawn rows can be restored)` },
          { status: 400 },
        );
      }
      const nowIso = new Date().toISOString();
      const { data: updated, error: restoreErr } = await service
        .from('student_applications')
        .update({ status: 'Submitted', reviewed_at: nowIso })
        .eq('id', id)
        .select('*')
        .single();
      if (restoreErr) {
        return NextResponse.json({ error: restoreErr.message }, { status: 400 });
      }
      // Best-effort stage_history write so the timeline tab shows
      // the restore event. Mirrors the Phase 107 PATCH path —
      // failure here doesn't fail the user-visible restore.
      try {
        await service.from('application_stage_history').insert({
          application_id: id,
          from_status: fromStatus,
          to_status: 'Submitted',
          actor_id: auth.user.id,
          actor_email: auth.user.email || null,
          actor_role: 'admin',
          note: 'Restored from Withdrawn',
        });
      } catch (eventErr) {
        console.warn('[admin/applications PATCH restore] event insert failed:', eventErr);
      }
      return NextResponse.json({ success: true, application: updated });
    }

    // Whitelist real student_applications columns. The old blocklist
    // (only 4 keys excluded) passed anything through — including the
    // edit page's bogus `university`/`program` keys, which made every
    // save fail with a PostgREST "column not found" 400.
    const UPDATABLE = new Set([
      'slug',
      'university_id', 'university_name', 'university_name_cn',
      'program_id', 'program_name', 'program_name_cn',
      'degree', 'degree_level', 'intake',
      'status', 'priority',
      'submitted_at', 'reviewed_at', 'decision_date', 'decision',
      'decision_letter_url', 'student_notes', 'personal_statement',
      'additional_notes', 'admin_notes',
      'applicant_name', 'applicant_email', 'applicant_phone',
      'applicant_nationality',
      // Phase 107 — lead attribution + enrollment + timeline-visibility
      // fields are admin-managed. lead_id/lead_type are polymorphic;
      // the API layer (Batch 5) will validate the (id, type) pair before
      // insert. enrolled_at is only writable via /api/admin/applications/
      // [id]/enroll — the route below strips it from this payload.
      'lead_id', 'lead_type',
      'timeline_visible_to_student',
    ]);
    const updates: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(body)) {
      if (UPDATABLE.has(k)) updates[k] = v;
    }
    // Phase 107: enrolled_at is exclusively written via the /enroll
    // subroute so a stray PATCH cannot overwrite a completed enrollment
    // without the deposit/visa payload. Strip it here as defense in depth.
    delete (updates as Record<string, unknown>).enrolled_at;
    if (Object.keys(updates).length === 0) {
      return NextResponse.json({ error: 'No updatable fields' }, { status: 400 });
    }
    // Validate status if provided (S12.2)
    let newStatus: string | null = null;
    if (typeof updates.status === 'string') {
      if (!(ALLOWED_STATUSES as readonly string[]).includes(updates.status)) {
        return NextResponse.json(
          { error: `status must be one of: ${ALLOWED_STATUSES.join(', ')}` },
          { status: 400 },
        );
      }
      newStatus = updates.status;
    }

    const service = buildServiceClient();

    // Pre-read the current row: gives a real 404 for bad ids (the old
    // .single() on update returned a 400 for missing rows) and lets us
    // compare status before/after so a re-save that merely *contains*
    // the same status doesn't fire timeline events + emails again.
    const { data: before, error: beforeErr } = await service
      .from('student_applications')
      .select('id, status')
      .eq('id', id)
      .maybeSingle();
    if (beforeErr) {
      return NextResponse.json({ error: beforeErr.message }, { status: 500 });
    }
    if (!before) {
      return NextResponse.json({ error: 'Application not found' }, { status: 404 });
    }
    const statusChanged = newStatus !== null && newStatus !== before.status;
    if (statusChanged) {
      updates.reviewed_at = new Date().toISOString();
    }

    const { data, error } = await service
      .from('student_applications')
      .update(updates)
      .eq('id', id)
      .select('*')
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    // Audit trail: write a timeline event for the status change
    if (statusChanged && newStatus) {
      await insertTimelineEvent(service, {
        application_id: id,
        status: newStatus,
        notes: body.notes || `Status changed to ${newStatus} by admin.`,
        created_by: auth.user.id,
      });

      // Phase 107 — also write the structured stage_history row so the
      // admin Timeline tab has a clean source of stage transitions
      // (actor + from→to + optional internal marker) separate from the
      // free-text application_timeline notes. The two tables complement
      // each other; this batch keeps the legacy table write for
      // backward compatibility with the student timeline tab.
      const noteBody: string | null =
        typeof body.notes === 'string' && body.notes.trim().length > 0
          ? body.notes
          : null;
      const internalFlag = body.internal === true;
      const stageNote = noteBody
        ? internalFlag
          ? `[internal] ${noteBody}`
          : noteBody
        : internalFlag
          ? '[internal]'
          : null;
      const { error: stageErr } = await service
        .from('application_stage_history')
        .insert({
          application_id: id,
          from_status: before.status,
          to_status: newStatus,
          actor_id: auth.user.id,
          actor_email: auth.user.email ?? null,
          actor_role: 'admin',
          note: stageNote,
        });
      if (stageErr) {
        // Don't fail the response — the timeline row already succeeded.
        console.error('[admin/applications PATCH] stage_history insert failed:', stageErr);
      }

      // Email the applicant (fire-and-forget — never block the response
      // on email). Admin can opt out per-update with notify_applicant=false.
      const shouldNotify = body.notify_applicant !== false;
      if (shouldNotify) {
        // Determine recipient: linked student profile email first, fall
        // back to applicant_email (unlinked application).
        let toEmail: string | null = null;
        let applicantName: string | null = null;
        if (data.student_id) {
          const { data: profile } = await service
            .from('student_profiles')
            .select('email, first_name, last_name')
            .eq('id', data.student_id)
            .maybeSingle();
          if (profile) {
            toEmail = profile.email || null;
            applicantName = [profile.first_name, profile.last_name]
              .filter(Boolean)
              .join(' ') || null;
          }
        }
        if (!toEmail) {
          toEmail = (data as { applicant_email?: string | null }).applicant_email || null;
          applicantName =
            (data as { applicant_name?: string | null }).applicant_name || applicantName;
        }

        // Send the email in the background. We deliberately do NOT await
        // this — a Resend outage shouldn't break the admin's status
        // update. Errors are logged but swallowed.
        if (toEmail) {
          notifyApplicantOnStatusChange({
            toEmail,
            applicantName,
            universityName:
              (data as { university_name?: string | null }).university_name || null,
            programName: (data as { program_name?: string | null }).program_name || null,
            degree:
              (data as { degree_level?: string | null }).degree_level ||
              (data as { degree?: string | null }).degree ||
              null,
            intake: (data as { intake?: string | null }).intake || null,
            applicationNumber:
              (data as { application_number?: string | null }).application_number || null,
            newStatus,
            extraNote: body.applicant_note || null,
          }).catch((emailErr) => {
            console.error('[admin/applications PATCH] applicant email failed:', emailErr);
          });

          // S29: insert a student_notification row so the in-app
          // inbox surfaces this status change. The table has been
          // sitting empty for v1 because no code path was writing
          // to it. Skip for unlinked applications (no student_id
          // row to attach the notification to).
          if (data.student_id) {
            const { error: snErr } = await service.from('student_notifications').insert({
              student_id: data.student_id,
              title: studentNotificationTitle(newStatus),
              message: studentNotificationMessage(
                newStatus,
                (data as { university_name?: string | null }).university_name || 'the university',
                (data as { program_name?: string | null }).program_name || null,
              ),
              type: 'status_change',
              // Phase 1.2: deep-link to the application detail so
              // the student lands directly on the app whose
              // status just changed. The inbox row click uses
              // this same URL.
              link_url: `/student/applications/${id}`,
            });
            if (snErr) {
              console.error('[admin/applications PATCH] student_notification insert failed:', snErr);
            }
          }

        }
      }
    }

    return NextResponse.json({ application: data });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

export async function DELETE(
  request: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  if (!getServerEnv().serviceKey) {
    return NextResponse.json({ error: 'Supabase not configured' }, { status: 503 });
  }
  const auth = await requireAdmin(request);
  if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status });

  const { id } = await context.params;
  if (!id) return NextResponse.json({ error: 'Missing id' }, { status: 400 });

  try {
    // "Cancel" via status='Withdrawn' — preserves the row for audit.
    const service = buildServiceClient();
    const { data, error } = await service
      .from('student_applications')
      .update({ status: 'Withdrawn', reviewed_at: new Date().toISOString() })
      .eq('id', id)
      .select('id, status, reviewed_at')
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }
    return NextResponse.json({ success: true, application: data });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
